Repository fifteen-night/fifteen-night-backend, pull requests merged in 2025-03, with the labels that each got.

#7 #6 feat: gateway 서비스 추가 및 기본 라우팅 설정
  gateway/.gitattributes
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle
  gateway/src/main/java/com/fn/eureka/gateway/GatewayApplication.java
  gateway/src/main/resources/application.yml
  gateway/src/test/java/com/fn/eureka/gateway/GatewayApplicationTests.java
Labels: feature

#13 #11 feat: Swagger 설정 추가
  gateway/build.gradle
  gateway/src/main/java/com/fn/gateway/GatewayApplication.java
  gateway/src/main/resources/application.yml
  gateway/src/test/java/com/fn/gateway/GatewayApplicationTests.java
Labels: feature

#14 #4 feat: common - Exception, BaseEntity
  .gitignore
  build.gradle
  common/build.gradle
  common/src/main/java/com/fn/common/global/BaseEntity.java
  common/src/main/java/com/fn/common/global/config/JpaConfig.java
  common/src/main/java/com/fn/common/global/exception/BadRequestException.java
  common/src/main/java/com/fn/common/global/exception/ConflictException.java
  common/src/main/java/com/fn/common/global/exception/ErrorResponse.java
  common/src/main/java/com/fn/common/global/exception/ForbiddenException.java
  common/src/main/java/com/fn/common/global/exception/GlobalExceptionAdvice.java
  common/src/main/java/com/fn/common/global/exception/NotFoundException.java
  common/src/main/java/com/fn/common/global/exception/UnauthorizedException.java
  company/build.gradle
  company/gradle/wrapper/gradle-wrapper.jar
  company/gradle/wrapper/gradle-wrapper.properties
  company/src/main/java/com/fn/eureka/client/company/CompanyApplication.java
  company/src/main/java/com/fn/eureka/client/company/controller/CompanyController.java
  company/src/main/java/com/fn/eureka/client/company/entity/Company.java
  company/src/main/java/com/fn/eureka/client/company/entity/CompanyType.java
  company/src/main/java/com/fn/eureka/client/company/service/CompanyService.java
  company/src/main/resources/application.yml
  company/src/test/java/com/fn/eureka/client/company/CompanyApplicationTests.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: feature

#15 #12 feat: 업체 생성
  company/.gitignore
  company/build.gradle
  company/src/main/java/com/fn/eureka/client/company/CompanyApplication.java
  company/src/main/java/com/fn/eureka/client/company/client/HubServiceClient.java
  company/src/main/java/com/fn/eureka/client/company/client/UserServiceClient.java
  company/src/main/java/com/fn/eureka/client/company/controller/CompanyController.java
  company/src/main/java/com/fn/eureka/client/company/dto/CompanyCreateRequestDto.java
  company/src/main/java/com/fn/eureka/client/company/dto/CompanyCreateResponseDto.java
  company/src/main/java/com/fn/eureka/client/company/dto/HubResponseDto.java
  company/src/main/java/com/fn/eureka/client/company/dto/UserResponseDto.java
  company/src/main/java/com/fn/eureka/client/company/entity/Company.java
  company/src/main/java/com/fn/eureka/client/company/repository/CompanyRepository.java
  company/src/main/java/com/fn/eureka/client/company/service/CompanyService.java
  company/src/main/java/com/fn/eureka/client/company/service/CompanyServiceImpl.java
  company/src/main/resources/application.yml
Labels: feature

#22 feat/#10_회원가입 기능 구현 및 중복 설정 제거
  .gitignore
  gateway/.gitattributes
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle
  settings.gradle
  user/build.gradle
  user/src/main/java/com/fn/eureka/client/user/UserApplication.java
  user/src/main/java/com/fn/eureka/client/user/application/dto/ApiResponseDto.java
  user/src/main/java/com/fn/eureka/client/user/application/dto/auth/request/UserSignUpRequestDto.java
  user/src/main/java/com/fn/eureka/client/user/application/dto/auth/response/UserSignUpResponseDto.java
  user/src/main/java/com/fn/eureka/client/user/application/exception/ErrorMessage.java
  user/src/main/java/com/fn/eureka/client/user/application/service/AuthService.java
  user/src/main/java/com/fn/eureka/client/user/domain/entity/User.java
  user/src/main/java/com/fn/eureka/client/user/domain/entity/UserRole.java
  user/src/main/java/com/fn/eureka/client/user/domain/repository/UserRepository.java
  user/src/main/java/com/fn/eureka/client/user/libs/config/WebConfig.java
  user/src/main/java/com/fn/eureka/client/user/presentation/controller/AuthController.java
  user/src/main/resources/application.yml
  user/src/test/java/com/fn/eureka/client/user/UserApplicationTests.java
Labels: feature

#26 #20 feat: 업체 삭제
  common/src/main/java/com/fn/common/global/BaseEntity.java
  company/src/main/java/com/fn/eureka/client/company/CompanyApplication.java
  company/src/main/java/com/fn/eureka/client/company/application/controller/CompanyController.java
  company/src/main/java/com/fn/eureka/client/company/application/dto/CompanyRequestDto.java
  company/src/main/java/com/fn/eureka/client/company/application/dto/CompanyResponseDto.java
  company/src/main/java/com/fn/eureka/client/company/application/dto/HubResponseDto.java
  company/src/main/java/com/fn/eureka/client/company/application/dto/UserResponseDto.java
  company/src/main/java/com/fn/eureka/client/company/domain/entity/Company.java
  company/src/main/java/com/fn/eureka/client/company/domain/entity/CompanyType.java
  company/src/main/java/com/fn/eureka/client/company/domain/repository/CompanyQueryRepository.java
  company/src/main/java/com/fn/eureka/client/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/fn/eureka/client/company/infrastructure/HubServiceClient.java
  company/src/main/java/com/fn/eureka/client/company/infrastructure/UserServiceClient.java
  company/src/main/java/com/fn/eureka/client/company/presentation/CompanyService.java
  company/src/main/java/com/fn/eureka/client/company/presentation/CompanyServiceImpl.java
Labels: feature

#29 Feat/#9 루트경로 생성 (허브 이름으로 직접 저장)
  delivery-service/.gitattributes
  delivery-service/.gitignore
  delivery-service/build.gradle
  delivery-service/docker-compose-local.yml
  delivery-service/gradle/wrapper/gradle-wrapper.jar
  delivery-service/gradle/wrapper/gradle-wrapper.properties
  delivery-service/gradlew
  delivery-service/gradlew.bat
  delivery-service/settings.gradle
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/DeliveryServiceApplication.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/HubToHubRepository.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/HubToHubService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/request/CreateHubToHubRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/response/CreateHubToHubResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/config/OpenFeignConfig.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/HubToHub.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/exception/HubToHubException.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/infrastructure/NaverMapService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/HubToHubController.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/dto/request/NaverMapDirReqestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/dto/response/NaverMapDirResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/dto/response/NaverMapGeoResponseDto.java
  delivery-service/src/main/resources/application.yml
  delivery-service/src/main/resources/db/data.sql
  delivery-service/src/main/resources/properties/datasource.yml
  delivery-service/src/main/resources/properties/jpa.yml
  delivery-service/src/main/resources/properties/key.yml
  delivery-service/src/test/java/com/fn/eureka/client/deliveryservice/DeliveryServiceApplicationTests.java
Labels: enhancement, feature

#27 feat/#25_로그인 기능 구현
  gateway/build.gradle
  gateway/src/main/java/com/fn/gateway/filter/AuthenticationFilter.java
  gateway/src/main/java/com/fn/gateway/util/JwtUtil.java
  gateway/src/main/resources/application.yml
  settings.gradle
  user/build.gradle
  user/src/main/java/com/fn/eureka/client/user/application/dto/auth/request/UserSignInRequestDto.java
  user/src/main/java/com/fn/eureka/client/user/application/dto/auth/response/UserSignInResponseDto.java
  user/src/main/java/com/fn/eureka/client/user/application/exception/CustomJwtException.java
  user/src/main/java/com/fn/eureka/client/user/application/exception/ErrorMessage.java
  user/src/main/java/com/fn/eureka/client/user/application/exception/JwtExceptionMessage.java
  user/src/main/java/com/fn/eureka/client/user/application/service/AuthService.java
  user/src/main/java/com/fn/eureka/client/user/domain/repository/UserRepository.java
  user/src/main/java/com/fn/eureka/client/user/infrastructure/filter/AuthenticationFilter.java
  user/src/main/java/com/fn/eureka/client/user/infrastructure/security/RequestUserDetails.java
  user/src/main/java/com/fn/eureka/client/user/infrastructure/security/SecurityConfig.java
  user/src/main/java/com/fn/eureka/client/user/libs/util/JwtUtil.java
  user/src/main/java/com/fn/eureka/client/user/presentation/controller/AuthController.java
  user/src/main/resources/application.yml
Labels: feature

#33 Feat/#31 read user
  user/src/main/java/com/fn/eureka/client/user/application/dto/user/response/UserGetResponseDto.java
  user/src/main/java/com/fn/eureka/client/user/application/exception/ErrorMessage.java
  user/src/main/java/com/fn/eureka/client/user/application/service/UserService.java
  user/src/main/java/com/fn/eureka/client/user/domain/repository/UserRepository.java
  user/src/main/java/com/fn/eureka/client/user/presentation/controller/UserController.java
Labels: feature

#34 Feat/#30 find one hub to hub
  .gitignore
  common/build.gradle
  common/src/main/java/com/fn/common/global/BaseEntity.java
  common/src/main/java/com/fn/common/global/dto/CommonPageResponse.java
  common/src/main/java/com/fn/common/global/dto/CommonResponse.java
  common/src/main/java/com/fn/common/global/exception/CustomApiException.java
  common/src/main/java/com/fn/common/global/exception/type/BaseException.java
  common/src/main/java/com/fn/common/global/exception/type/ExceptionType.java
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  delivery-service/build.gradle
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/DeliveryServiceApplication.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/HubToHubRepository.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/HubToHubService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/request/CreateHubToHubRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/response/CreateHubToHubResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/response/GetHubToHubResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/HubToHub.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/exception/HubToHubException.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/infrastructure/NaverMapService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/HubToHubController.java
  docker-compose-local.yml
  resources/conventions/naver-intellij-formatter.xml
  resources/db/schema.sql
  settings.gradle
Labels: enhancement, feature

#44 Feat/#40 상품 리스트 조회
  company-service/src/main/java/com/fn/eureka/client/companyservice/domain/repository/CompanyQueryRepository.java
  product-service/src/main/java/com/fn/eureka/client/productservice/application/ProductController.java
  product-service/src/main/java/com/fn/eureka/client/productservice/domain/ProductQueryRepository.java
  product-service/src/main/java/com/fn/eureka/client/productservice/domain/repository/ProductQueryRepository.java
  product-service/src/main/java/com/fn/eureka/client/productservice/domain/repository/ProductRepository.java
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/ProductService.java
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/ProductServiceImpl.java
  product-service/src/main/resources/application.yml
Labels: feature

#50 #41 fix: 상품 수정 Conflict 해결
  product-service/src/main/java/com/fn/eureka/client/productservice/ProductServiceApplication.java
  product-service/src/main/java/com/fn/eureka/client/productservice/application/ProductController.java
  product-service/src/main/java/com/fn/eureka/client/productservice/domain/Product.java
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/ProductService.java
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/ProductServiceImpl.java
Labels: bug, feature

#49 Feat/#47 유저 삭제
  common/build.gradle
  common/src/main/java/com/fn/common/global/BaseEntity.java
  common/src/main/java/com/fn/common/global/audit/SecurityContextHelper.java
  common/src/main/java/com/fn/common/global/config/JpaConfig.java
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  user-service/src/main/java/com/fn/eureka/client/userservice/application/service/UserService.java
  user-service/src/main/java/com/fn/eureka/client/userservice/infrastructure/filter/AuthenticationFilter.java
  user-service/src/main/java/com/fn/eureka/client/userservice/infrastructure/security/RequestUserDetails.java
  user-service/src/main/java/com/fn/eureka/client/userservice/infrastructure/security/SecurityConfig.java
  user-service/src/main/java/com/fn/eureka/client/userservice/presentation/controller/UserController.java
Labels: bug, enhancement, feature

#57 Feat/#51 상품 삭제
  company-service/src/main/java/com/fn/eureka/client/companyservice/CompanyServiceApplication.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/application/CompanyService.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/application/CompanyServiceImpl.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/domain/entity/Company.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/domain/repository/CompanyQueryRepository.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/infrastructure/HubServiceClient.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/infrastructure/UserServiceClient.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/presentation/CompanyController.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/presentation/dto/CompanyRequestDto.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/presentation/dto/CompanyResponseDto.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/presentation/dto/HubResponseDto.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/presentation/dto/UserResponseDto.java
  product-service/build.gradle
  product-service/src/main/java/com/fn/eureka/client/productservice/ProductServiceApplication.java
  product-service/src/main/java/com/fn/eureka/client/productservice/application/ProductService.java
  product-service/src/main/java/com/fn/eureka/client/productservice/application/ProductServiceImpl.java
  product-service/src/main/java/com/fn/eureka/client/productservice/config/SpringSecurityConfig.java
  product-service/src/main/java/com/fn/eureka/client/productservice/domain/Product.java
  product-service/src/main/java/com/fn/eureka/client/productservice/domain/repository/ProductQueryRepository.java
  product-service/src/main/java/com/fn/eureka/client/productservice/infrastructure/CompanyServiceClient.java
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/ProductController.java
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/dto/CompanyInfoDto.java
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/dto/ProductRequestDto.java
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/dto/ProductResponseDto.java
Labels: feature

#55 Feat/#54 refactor user
  user-service/src/main/java/com/fn/eureka/client/userservice/application/service/AuthService.java
  user-service/src/main/java/com/fn/eureka/client/userservice/application/service/UserService.java
  user-service/src/main/java/com/fn/eureka/client/userservice/libs/config/PasswordEncoderConfig.java
  user-service/src/main/java/com/fn/eureka/client/userservice/presentation/controller/AuthController.java
  user-service/src/main/java/com/fn/eureka/client/userservice/presentation/controller/UserController.java
  user-service/src/main/resources/db/create-user.sql
  user-service/src/main/resources/db/data.sql
  user-service/src/main/resources/properties/datasource.yml
  user-service/src/main/resources/properties/jpa.yml
Labels: enhancement

#60 Feat/#53 update hub to hub
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/HubToHubRepository.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/HubToHubService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/request/UpdateHubToHubRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/response/UpdateHubToHubResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/config/HubRouteScheduler.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/HubToHub.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/util/TimeUtils.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/HubToHubController.java
  delivery-service/src/main/resources/application.yml
Labels: feature

#65 Feat/#61 create delivery
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/DeliveryRepository.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/DeliveryService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/HubToHubRepository.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/HubToHubService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/delivery/dto/request/CreateDeliveryRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/delivery/dto/response/CreateDeliveryResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/route/dto/request/CreateHubToHubRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/route/dto/request/UpdateHubToHubRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/route/dto/response/CreateHubToHubResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/route/dto/response/DeleteHubToHubResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/route/dto/response/GetAllHubToHubResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/route/dto/response/GetHubToHubResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/route/dto/response/UpdateHubToHubResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/config/HubRouteScheduler.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/delivery/Delivery.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/delivery/DeliveryStatus.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/route/HubToHub.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/service/DeliveryServiceImpl.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/service/HubToHubServiceImpl.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/exception/DeliveryException.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/DeliveryController.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/HubToHubController.java
Labels: enhancement, feature

#64 #63 feat: slack - 메시지 조회 기능 구현
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  slack-service/build.gradle
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/dto/response/SlackGetResponseDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/exception/SlackException.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/service/SlackService.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/domain/repository/SlackRepository.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/presentation/controller/SlackController.java
Labels: feature

#68 #67 feat: slack - 메시지 수정 기능 구현
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/dto/request/SlackUpdateRequestDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/dto/response/SlackUpdateResponseDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/service/SlackService.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/domain/entity/Slack.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/presentation/controller/SlackController.java
Labels: feature

#69 Feat/#42 hub stock 에그리거트 루트 도입 및 조회, 수정, 삭제 기능
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  hub-service/build.gradle
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/HubService.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/dto/response/ReadHubResponse.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/config/SecurityConfig.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/domain/Hub.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/HubRepositoryCustom.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/HubRepositoryCustomImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/HubServiceImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/presentation/HubController.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/application/HubStockService.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/application/dto/mapper/HubStockMapper.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/application/dto/request/UpdateHubStockRequest.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/application/dto/response/ReadHubStockResponse.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/domain/HubStock.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/domain/repository/HubStockRepository.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/infrastructure/HubStockServiceImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/presentation/HubStockController.java
  hub-service/src/main/resources/application.yml
Labels: feature

#75 #66 feat: delivery-service 삭제 API 구현
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/DeliveryService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/delivery/dto/response/DeleteDeliveryResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/service/DeliveryServiceImpl.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/DeliveryController.java
Labels: feature

#77 Feat/#76 update delivery
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/DeliveryService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/delivery/dto/request/UpdateDeliveryRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/delivery/dto/response/UpdateDeliveryResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/delivery/Delivery.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/service/DeliveryServiceImpl.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/DeliveryController.java
Labels: feature

#84 Feat/#81 주문 조회
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/CompanyServiceApplication.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/application/CompanyService.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/application/CompanyServiceImpl.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/config/AuthenticationFilter.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/domain/repository/CompanyQueryRepository.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/presentation/CompanyController.java
  order-service/build.gradle
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/OrderService.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/OrderServiceImpl.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/dto/CompanyInfoDto.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/dto/DeliveryRequestDto.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/dto/DeliveryResponseDto.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/dto/HubStockResponseDto.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/dto/OrderResponseDto.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/dto/UserResponseDto.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/model/Order.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/repository/OrderQueryRepository.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/repository/OrderRepository.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/service/OrderService.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/CompanyServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/CompanyServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/DeliveryServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/HubServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/UserServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/config/AuthenticationFilter.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/config/RequestUserDetails.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/config/SecurityConfig.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/exception/OrderException.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/repository/OrderQueryRepositoryImpl.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/service/OrderServiceImpl.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/presentation/OrderController.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/presentation/request/OrderRequestDto.java
  order-service/src/main/resources/application.yml
Labels: feature

#85 Feat/#74 hub&hub stock - 검증, 클라이언트 및 내부 서비스용 메서드 추가
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/HubServiceApplication.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/GeoClientService.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/HubService.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/ProductClientService.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/UserClientService.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/dto/request/CheckHubManagerRequest.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/dto/request/CreateHubRequest.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/dto/request/UpdateHubRequest.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/dto/response/CheckHubManagerResponse.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/dto/response/ReadProductResponse.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/dto/response/ReadUserResponse.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/config/GeoClientConfig.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/config/QuerydslConfig.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/domain/repository/HubRepository.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/exception/HubException.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/client/GeoClient.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/client/ProductClient.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/client/UserClient.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/repository/HubRepositoryCustom.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/repository/HubRepositoryCustomImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/service/GeoClientServiceImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/service/HubServiceImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/service/ProductClientServiceImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/service/UserClientServiceImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/presentation/HubController.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/application/dto/request/CreateHubStockRequest.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/application/dto/response/CreateHubStockResponse.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub_stock/exception/HubStockException.java
Labels: feature

#86 Feat/#83 주문 수정
  company-service/src/main/java/com/fn/eureka/client/companyservice/application/CompanyService.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/application/CompanyServiceImpl.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/domain/repository/CompanyQueryRepository.java
  company-service/src/main/java/com/fn/eureka/client/companyservice/presentation/CompanyController.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/model/Order.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/service/OrderService.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/CompanyServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/exception/OrderException.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/repository/OrderQueryRepositoryImpl.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/service/OrderServiceImpl.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/presentation/OrderController.java
Labels: feature

#89 Feat/#88 read delivery manager
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/dto/response/DeliveryManagerGetResponseDto.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/exception/DeliveryManagerException.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/service/DeliveryManagerService.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/domain/entity/DeliveryManagerType.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/domain/repository/DeliveryManagerRepository.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/infrastructure/client/UserClient.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/presentation/DeliveryManagerController.java
Labels: feature

#93 #90 feat: delivery-manager - 수정 기능 구현
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/dto/request/DeliveryManagerUpdateRequestDto.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/dto/response/DeliveryManagerUpdateResponseDto.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/service/DeliveryManagerService.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/domain/entity/DeliveryManager.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/presentation/DeliveryManagerController.java
Labels: feature

#91 Feat/#87 주문 삭제
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/dto/OrderResponseDto.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/model/Order.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/repository/OrderQueryRepository.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/service/OrderService.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/DeliveryServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/HubServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/UserServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/repository/OrderQueryRepositoryImpl.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/service/OrderServiceImpl.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/presentation/OrderController.java
Labels: feature

#95 Feat/#94 delete delivery manager
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  delivery-manager-service/build.gradle
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/dto/request/DeliveryManagerSearchCondition.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/service/DeliveryManagerService.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/service/DeliveryManagerServiceImpl.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/domain/repository/DeliveryManagerRepository.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/domain/repository/DeliveryManagerRepositoryCustom.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/domain/repository/DeliveryManagerRepositoryImpl.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/presentation/DeliveryManagerController.java
  delivery-manager-service/src/main/resources/application.yml
  delivery-manager-service/src/test/java/com/fn/eureka/client/deliverymanagerservice/DeliveryManagerServiceApplicationTests.java
Labels: feature

#102 Feat/#98 assign delivery manager
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/exception/DeliveryManagerException.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/service/DeliveryManagerService.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/service/DeliveryManagerServiceImpl.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/domain/repository/DeliveryManagerRepository.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/presentation/DeliveryManagerController.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/domain/entity/Slack.java
Labels: feature

#106 Feat/#74 hub adv sql 파일 및 외부 서비스용 메서드 추가
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/application/HubService.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/domain/repository/HubRepository.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/service/HubServiceImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/presentation/HubController.java
  hub-service/src/main/resources/hub_data.sql
Labels: feature

#111 Feat/#108 refactor delivery manager
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/application/service/DeliveryManagerServiceImpl.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/infrastructure/client/HubClient.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/infrastructure/security/DMSecurityConfig.java
  delivery-manager-service/src/main/java/com/fn/eureka/client/deliverymanagerservice/presentation/DeliveryManagerController.java
Labels: enhancement, feature

#112 Feat/#74 feat:hub - 사용자 검증기능 추가
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/config/SecurityConfig.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/client/GeoClient.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/config/GeoClientConfig.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/config/SecurityConfig.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/filter/AuthenticationFilter.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/security/UserDetailsImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/presentation/HubController.java
Labels: feature

#113 Feat/#101 ai
  http/ai.http
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/dto/ProductResponseDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/SlackServiceApplication.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/dto/request/DeliveryInfoDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/dto/request/GeminiRequestDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/dto/response/DeliveryManagerInfoDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/dto/response/GeminiResponseDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/dto/response/OrderInfoDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/dto/response/UserInfoDto.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/exception/SlackException.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/service/GeminiService.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/infrastructure/client/DeliveryManagerServiceClient.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/infrastructure/client/GeminiClient.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/infrastructure/client/OrderServiceClient.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/infrastructure/client/UserServiceClient.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/infrastructure/filter/AuthenticationFilter.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/infrastructure/security/SlackSecurityConfig.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/presentation/controller/SlackController.java
  slack-service/src/main/resources/application.yml
Labels: feature

#118 Feat/#110 search delivery route
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/delivery/request/UpdateDeliveryRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/delivery/response/GetAllDeliveryResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/delivery/response/GetDeliveryResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/delivery/response/UpdateDeliveryResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/deliveryRoute/response/GetAllDeliveryRouteResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/deliveryRoute/response/GetDeliveryRouteResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/deliveryRoute/response/UpdateDeliveryRouteResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/deliveryRouteSequence/request/UpdateSequenceRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/deliveryRouteSequence/response/GetAllSequenceResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/deliveryRouteSequence/response/GetSequenceResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/deliveryRouteSequence/response/UpdateSequenceResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/model/delivery/Delivery.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/model/deliveryRoute/DeliveryRoute.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/model/deliveryRouteSequence/DeliveryRouteSequence.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/repository/DeliveryRepositoryCustom.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/repository/DeliveryRepositoryImpl.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/repository/DeliveryRouteRepository.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/repository/DeliveryRouteSequenceRepository.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/service/DeliveryServiceImpl.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/exception/DeliveryException.java
Labels: enhancement, feature

#123 #114 feat: delivery-service feign클라이언트 통신
  common/src/main/java/com/fn/common/global/config/FeignInterceptor.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/delivery/request/CreateDeliveryRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/deliveryRoute/request/CreateDeliveryRouteRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/deliveryRouteSequence/request/CreateSequenceRequestDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/model/deliveryRoute/DeliveryRoute.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/service/DeliveryServiceImpl.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/service/HubToHubServiceImpl.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/infrastructure/client/DeliveryManagerServiceClient.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/infrastructure/client/HubServiceClient.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/infrastructure/client/NaverMapService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/dto/response/HubClientResponseDto.java
Labels: feature

#129 #119 feat: delivery-service 추가 기능
  common/src/main/java/com/fn/common/global/success/SuccessCode.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/dto/delivery/response/QueryAllDeliveriesResponseDto.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/application/service/DeliveryService.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/domain/service/DeliveryServiceImpl.java
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/presentation/DeliveryController.java
Labels: feature

#130 feat/#74 hub adv
  common/src/main/java/com/fn/common/global/dto/CommonResponse.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/infrastructure/service/HubServiceImpl.java
  hub-service/src/main/java/com/fn/eureka/client/hubservice/hub/presentation/HubController.java
  hub-service/src/main/resources/application.yml
  hub-service/src/main/resources/hub_data.sql
  user-service/src/main/java/com/fn/eureka/client/userservice/application/dto/auth/request/UserSignInRequestDto.java
  user-service/src/main/java/com/fn/eureka/client/userservice/application/dto/auth/request/UserSignUpRequestDto.java
Labels: feature

#139 Feat/#138 last setting
  company-service/build.gradle
  company-service/src/main/java/com/fn/eureka/client/companyservice/presentation/CompanyController.java
  company-service/src/main/resources/application.yml
  order-service/build.gradle
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/dto/DeliveriesUUIDDto.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/application/dto/HubStockUpdateDto.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/domain/repository/OrderQueryRepository.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/DeliveryServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/client/HubServiceClient.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/config/RequestUserDetails.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/exception/OrderException.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/repository/OrderQueryRepositoryImpl.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/infrastructure/service/OrderServiceImpl.java
  order-service/src/main/java/com/fn/eureka/client/orderservice/presentation/OrderController.java
  order-service/src/main/resources/application.yml
  product-service/build.gradle
  product-service/src/main/java/com/fn/eureka/client/productservice/infrastructure/config/AuthenticationFilter.java
  product-service/src/main/java/com/fn/eureka/client/productservice/infrastructure/config/RequestUserDetails.java
  product-service/src/main/java/com/fn/eureka/client/productservice/infrastructure/config/SecurityConfig.java
  product-service/src/main/java/com/fn/eureka/client/productservice/infrastructure/service/ProductServiceImpl.java
  product-service/src/main/java/com/fn/eureka/client/productservice/presentation/ProductController.java
  product-service/src/main/resources/application.yml
Labels: bug, feature

#140 Feat/#136 refactor slack
  slack-service/build.gradle
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/service/GeminiService.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/service/SlackService.java
  slack-service/src/main/java/com/fn/eureka/client/slackservice/application/service/SlackServiceImpl.java
  slack-service/src/main/resources/application.yml
Labels: enhancement

#142 Feat/#137 setting zipken
  delivery-service/Dockerfile
  delivery-service/build.gradle
  delivery-service/src/main/java/com/fn/eureka/client/deliveryservice/infrastructure/security/RequestUserDetails.java
  delivery-service/src/main/resources/application.yml
  gradlew
Labels: feature

#143 feat/#74 hub adv - zipkin, swagger 추가
  hub-service/build.gradle
  hub-service/src/main/resources/application.yml
Labels: feature

#144 #137 refactor: delivery-service dockerfile 설정변경
  build.gradle
  delivery-manager-service/src/test/java/com/fn/eureka/client/deliverymanagerservice/DeliveryManagerServiceApplicationTests.java
  delivery-service/Dockerfile
  delivery-service/build.gradle
  delivery-service/src/test/java/com/fn/eureka/client/deliveryservice/DeliveryServiceApplicationTests.java
  gateway/src/test/java/com/fn/gateway/GatewayApplicationTests.java
  hub-service/src/test/java/com/fn/eureka/hubservice/HubServiceApplicationTests.java
  order-service/src/test/java/com/fn/eureka/client/orderservice/OrderServiceApplicationTests.java
  server/src/test/java/com/fn/eureka/server/ServerApplicationTests.java
  slack-service/src/test/java/com/fn/eureka/client/slackservice/SlackServiceApplicationTests.java
  user-service/src/test/java/com/fn/eureka/client/userservice/UserServiceApplicationTests.java
Labels: enhancement, feature
